
try:
    print(a)
except Exception as e:
    print('Something went wrong, please try again')

print("hello")